/*
 QUnit v1.7.0pre - A JavaScript Unit Testing Framework

 http://docs.jquery.com/QUnit

 Copyright (c) 2012 John Resig, Jorn Zaefferer
 Dual licensed under the MIT (MIT-LICENSE.txt)
 or GPL (GPL-LICENSE.txt) licenses.
*/
(function(j){var q,v;function w(a){l(this,a);this.assertions=[];this.testNumber=++w.count}function E(){d.autorun=!0;d.currentModule&&m("moduleDone",e,{name:d.currentModule,failed:d.moduleStats.bad,passed:d.moduleStats.all-d.moduleStats.bad,total:d.moduleStats.all});var a,c;a=k("qunit-banner");c=k("qunit-tests");var b=+new Date-d.started,f=d.stats.all-d.stats.bad,h=["Tests completed in ",b," milliseconds.<br/><span class='passed'>",f,"</span> tests of <span class='total'>",d.stats.all,"</span> passed, <span class='failed'>",
d.stats.bad,"</span> failed."].join("");if(a)a.className=d.stats.bad?"qunit-fail":"qunit-pass";if(c)k("qunit-testresult").innerHTML=h;if(d.altertitle&&"undefined"!==typeof document&&document.title)document.title=[d.stats.bad?"✖":"✔",document.title.replace(/^[\u2714\u2716] /i,"")].join(" ");if(d.reorder&&q&&0===d.stats.bad)for(a=0;a<sessionStorage.length;a++)c=sessionStorage.key(a++),0===c.indexOf("qunit-test-")&&sessionStorage.removeItem(c);m("done",e,{failed:d.stats.bad,passed:f,total:d.stats.all,
runtime:b})}function x(a,c){var c=c||3,b;if(a.stacktrace)return a.stacktrace.split("\n")[c+3];if(a.stack)return b=a.stack.split("\n"),/^error$/i.test(b[0])&&b.shift(),b[c];if(a.sourceURL)return/qunit.js$/.test(a.sourceURL)?void 0:a.sourceURL+":"+a.line}function u(a){try{throw Error();}catch(c){return x(c,a)}}function o(a){return!a?"":(a+"").replace(/[\&<>]/g,function(a){switch(a){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";default:return a}})}function r(a,c){d.queue.push(a);
d.autorun&&!d.blocking&&y(c)}function y(a){function c(){y(a)}var b=(new Date).getTime();for(d.depth=d.depth?d.depth+1:1;d.queue.length&&!d.blocking;)if(!v||0>=d.updateRate||(new Date).getTime()-b<d.updateRate)d.queue.shift()();else{j.setTimeout(c,13);break}d.depth--;a&&!d.blocking&&!d.queue.length&&0===d.depth&&E()}function z(){d.pollution=[];if(d.noglobals)for(var a in j)A.call(j,a)&&!/^qunit-test-output/.test(a)&&d.pollution.push(a)}function C(a,c){var b,d,e=a.slice();for(b=0;b<e.length;b++)for(d=
0;d<c.length;d++)if(e[b]===c[d]){e.splice(b,1);b--;break}return e}function l(a,c){for(var b in c)if(void 0===c[b])delete a[b];else if("constructor"!==b||a!==j)a[b]=c[b];return a}function s(a,c,b){a.addEventListener?a.addEventListener(c,b,!1):a.attachEvent?a.attachEvent("on"+c,b):b()}function k(a){return!!("undefined"!==typeof document&&document&&document.getElementById)&&document.getElementById(a)}function p(a){return function(c){d[a].push(c)}}function m(a,c,b){var f;if(e.hasOwnProperty(a))e[a].call(c,
b);else{f=d[a];for(a=0;a<f.length;a++)f[a].call(c,b)}}var e,d,F=0,D=Object.prototype.toString,A=Object.prototype.hasOwnProperty;v="undefined"!==typeof j.setTimeout;var B;try{sessionStorage.setItem("qunit-test-string","qunit-test-string"),sessionStorage.removeItem("qunit-test-string"),B=!0}catch(G){B=!1}q=B;w.count=0;w.prototype={init:function(){var a,c,b,d=k("qunit-tests");if(d)c=document.createElement("strong"),c.innerHTML=this.name,a=document.createElement("a"),a.innerHTML="Rerun",a.href=e.url({testNumber:this.testNumber}),
b=document.createElement("li"),b.appendChild(c),b.appendChild(a),b.className="running",b.id=this.id="qunit-test-output"+F++,d.appendChild(b)},setup:function(){this.module!==d.previousModule?(d.previousModule&&m("moduleDone",e,{name:d.previousModule,failed:d.moduleStats.bad,passed:d.moduleStats.all-d.moduleStats.bad,total:d.moduleStats.all}),d.previousModule=this.module,d.moduleStats={all:0,bad:0},m("moduleStart",e,{name:this.module})):d.autorun&&m("moduleStart",e,{name:this.module});d.current=this;
this.testEnvironment=l({setup:function(){},teardown:function(){}},this.moduleTestEnvironment);m("testStart",e,{name:this.testName,module:this.module});e.current_testEnvironment=this.testEnvironment;d.pollution||z();if(d.notrycatch)this.testEnvironment.setup.call(this.testEnvironment);else try{this.testEnvironment.setup.call(this.testEnvironment)}catch(a){e.pushFailure("Setup failed on "+this.testName+": "+a.message,x(a,1))}},run:function(){d.current=this;var a=k("qunit-testresult");if(a)a.innerHTML=
"Running: <br/>"+this.name;this.async&&e.stop();if(d.notrycatch)this.callback.call(this.testEnvironment,e.assert);else try{this.callback.call(this.testEnvironment,e.assert)}catch(c){e.pushFailure("Died on test #"+(this.assertions.length+1)+": "+c.message,x(c,1)),z(),d.blocking&&e.start()}},teardown:function(){d.current=this;if(d.notrycatch)this.testEnvironment.teardown.call(this.testEnvironment);else{try{this.testEnvironment.teardown.call(this.testEnvironment)}catch(a){e.pushFailure("Teardown failed on "+
this.testName+": "+a.message,x(a,1))}var c,b=d.pollution;z();c=C(d.pollution,b);0<c.length&&e.pushFailure("Introduced global variable(s): "+c.join(", "));c=C(b,d.pollution);0<c.length&&e.pushFailure("Deleted global variable(s): "+c.join(", "))}},finish:function(){d.current=this;null!=this.expected&&this.expected!=this.assertions.length?e.pushFailure("Expected "+this.expected+" assertions, but "+this.assertions.length+" were run",this.stack):null==this.expected&&!this.assertions.length&&e.pushFailure("Expected at least one assertion, but none were run - call expect(0) to accept zero assertions.",
this.stack);var a,c,b,f,h,g,i=this,n=c=0;h=k("qunit-tests");d.stats.all+=this.assertions.length;d.moduleStats.all+=this.assertions.length;if(h){g=document.createElement("ol");for(f=0;f<this.assertions.length;f++)a=this.assertions[f],h=document.createElement("li"),h.className=a.result?"pass":"fail",h.innerHTML=a.message||(a.result?"okay":"failed"),g.appendChild(h),a.result?c++:(n++,d.stats.bad++,d.moduleStats.bad++);e.config.reorder&&q&&(n?sessionStorage.setItem("qunit-test-"+this.module+"-"+this.testName,
n):sessionStorage.removeItem("qunit-test-"+this.module+"-"+this.testName));if(0===n)g.style.display="none";b=document.createElement("strong");b.innerHTML=this.name+" <b class='counts'>(<b class='failed'>"+n+"</b>, <b class='passed'>"+c+"</b>, "+this.assertions.length+")</b>";s(b,"click",function(){var a=b.nextSibling.nextSibling;a.style.display="none"===a.style.display?"block":"none"});s(b,"dblclick",function(a){a=a&&a.target?a.target:j.event.srcElement;if("span"==a.nodeName.toLowerCase()||"b"==a.nodeName.toLowerCase())a=
a.parentNode;if(j.location&&"strong"===a.nodeName.toLowerCase())j.location=e.url({testNumber:i.testNumber})});h=k(this.id);h.className=n?"fail":"pass";h.removeChild(h.firstChild);c=h.firstChild;h.appendChild(b);h.appendChild(c);h.appendChild(g)}else for(f=0;f<this.assertions.length;f++)this.assertions[f].result||(n++,d.stats.bad++,d.moduleStats.bad++);m("testDone",e,{name:this.testName,module:this.module,failed:n,passed:this.assertions.length-n,total:this.assertions.length});e.reset()},queue:function(){function a(){r(function(){c.setup()});
r(function(){c.run()});r(function(){c.teardown()});r(function(){c.finish()})}var c=this;r(function(){c.init()});e.config.reorder&&q&&+sessionStorage.getItem("qunit-test-"+this.module+"-"+this.testName)?a():r(a,!0)}};e={module:function(a,c){d.currentModule=a;d.currentModuleTestEnviroment=c},asyncTest:function(a,c,b){2===arguments.length&&(b=c,c=null);e.test(a,c,b,!0)},test:function(a,c,b,e){var h;h="<span class='test-name'>"+o(a)+"</span>";2===arguments.length&&(b=c,c=null);d.currentModule&&(h="<span class='module-name'>"+
d.currentModule+"</span>: "+h);h=new w({name:h,testName:a,expected:c,async:e,callback:b,module:d.currentModule,moduleTestEnvironment:d.currentModuleTestEnviroment,stack:u(2)});var g;var i=d.filter,n=h.module+": "+h.testName;d.testNumber?g=h.testNumber===d.testNumber:i?((g="!"!==i.charAt(0))||(i=i.slice(1)),g=-1!==n.indexOf(i)?g:!g):g=!0;g&&h.queue()},expect:function(a){d.current.expected=a},start:function(a){d.semaphore-=a||1;if(!(0<d.semaphore)){if(0>d.semaphore)d.semaphore=0;v?j.setTimeout(function(){if(!(0<
d.semaphore))d.timeout&&clearTimeout(d.timeout),d.blocking=!1,y(!0)},13):(d.blocking=!1,y(!0))}},stop:function(a){d.semaphore+=a||1;d.blocking=!0;if(d.testTimeout&&v)clearTimeout(d.timeout),d.timeout=j.setTimeout(function(){e.ok(!1,"Test timed out");d.semaphore=1;e.start()},d.testTimeout)}};e.assert={ok:function(a,c){if(!d.current)throw Error("ok() assertion outside test context, was "+u(2));var a=!!a,b,f={result:a,message:c},c=o(c||(a?"okay":"failed")),c="<span class='test-message'>"+c+"</span>";
if(!a&&(b=u(2)))f.source=b,c+="<table><tr class='test-source'><th>Source: </th><td><pre>"+o(b)+"</pre></td></tr></table>";m("log",e,f);d.current.assertions.push({result:a,message:c})},equal:function(a,c,b){e.push(c==a,a,c,b)},notEqual:function(a,c,b){e.push(c!=a,a,c,b)},deepEqual:function(a,c,b){e.push(e.equiv(a,c),a,c,b)},notDeepEqual:function(a,c,b){e.push(!e.equiv(a,c),a,c,b)},strictEqual:function(a,c,b){e.push(c===a,a,c,b)},notStrictEqual:function(a,c,b){e.push(c!==a,a,c,b)},raises:function(a,
c,b){var f,h=!1;"string"===typeof c&&(b=c,c=null);try{a.call(d.current.testEnvironment)}catch(g){f=g}f&&(c?"regexp"===e.objectType(c)?h=c.test(f):f instanceof c?h=!0:!0===c.call({},f)&&(h=!0):h=!0);e.push(h,f,null,b)}};l(e,e.assert);e.equals=function(){e.push(!1,!1,!1,"QUnit.equals has been deprecated since 2009 (e88049a0), use QUnit.equal instead")};e.same=function(){e.push(!1,!1,!1,"QUnit.same has been deprecated since 2009 (e88049a0), use QUnit.deepEqual instead")};(function(){function a(){}a.prototype=
e;e=new a;e.constructor=a})();d={queue:[],blocking:!0,hidepassed:!1,reorder:!0,altertitle:!0,urlConfig:["noglobals","notrycatch"],begin:[],done:[],log:[],testStart:[],testDone:[],moduleStart:[],moduleDone:[]};(function(){var a,c=j.location||{search:"",protocol:"file:"},b=c.search.slice(1).split("&"),f=b.length,h={},g;if(b[0])for(a=0;a<f;a++)g=b[a].split("="),g[0]=decodeURIComponent(g[0]),g[1]=g[1]?decodeURIComponent(g[1]):!0,h[g[0]]=g[1];e.urlParams=h;d.filter=h.filter;d.testNumber=parseInt(h.testNumber,
10)||null;e.isLocal="file:"===c.protocol})();if("undefined"===typeof exports)l(j,e),j.QUnit=e;l(e,{config:d,init:function(){l(d,{stats:{all:0,bad:0},moduleStats:{all:0,bad:0},started:+new Date,updateRate:1E3,blocking:!1,autostart:!0,autorun:!1,filter:"",queue:[],semaphore:0});var a,c,b;if(a=k("qunit"))a.innerHTML="<h1 id='qunit-header'>"+o(document.title)+"</h1><h2 id='qunit-banner'></h2><div id='qunit-testrunner-toolbar'></div><h2 id='qunit-userAgent'></h2><ol id='qunit-tests'></ol>";a=k("qunit-tests");
c=k("qunit-banner");b=k("qunit-testresult");if(a)a.innerHTML="";if(c)c.className="";b&&b.parentNode.removeChild(b);if(a)b=document.createElement("p"),b.id="qunit-testresult",b.className="result",a.parentNode.insertBefore(b,a),b.innerHTML="Running...<br/>&nbsp;"},reset:function(){var a;if(j.jQuery)jQuery("#qunit-fixture").html(d.fixture);else if(a=k("qunit-fixture"))a.innerHTML=d.fixture},triggerEvent:function(a,c,b){document.createEvent?(b=document.createEvent("MouseEvents"),b.initMouseEvent(c,!0,
!0,a.ownerDocument.defaultView,0,0,0,0,0,!1,!1,!1,!1,0,null),a.dispatchEvent(b)):a.fireEvent&&a.fireEvent("on"+c)},is:function(a,c){return e.objectType(c)==a},objectType:function(a){if("undefined"===typeof a)return"undefined";if(null===a)return"null";var c=D.call(a).match(/^\[object\s(.*)\]$/)[1]||"";switch(c){case "Number":return isNaN(a)?"nan":"number";case "String":case "Boolean":case "Array":case "Date":case "RegExp":case "Function":return c.toLowerCase()}if("object"===typeof a)return"object"},
push:function(a,c,b,f){if(!d.current)throw Error("assertion outside test context, was "+u());var h={result:a,message:f,actual:c,expected:b},f=o(f)||(a?"okay":"failed"),f="<span class='test-message'>"+f+"</span>";if(!a){b=o(e.jsDump.parse(b));c=o(e.jsDump.parse(c));f+="<table><tr class='test-expected'><th>Expected: </th><td><pre>"+b+"</pre></td></tr>";c!=b&&(f=f+("<tr class='test-actual'><th>Result: </th><td><pre>"+c+"</pre></td></tr>")+("<tr class='test-diff'><th>Diff: </th><td><pre>"+e.diff(b,c)+
"</pre></td></tr>"));if(c=u())h.source=c,f+="<tr class='test-source'><th>Source: </th><td><pre>"+o(c)+"</pre></td></tr>";f+="</table>"}m("log",e,h);d.current.assertions.push({result:!!a,message:f})},pushFailure:function(a,c){var b,f={result:!1,message:a},a=o(a)||"error";b="<span class='test-message'>"+a+"</span>";if(c)f.source=c,b+="<table><tr class='test-source'><th>Source: </th><td><pre>"+o(c)+"</pre></td></tr></table>";m("log",e,f);d.current.assertions.push({result:!1,message:b})},url:function(a){var a=
l(l({},e.urlParams),a),c,b="?";for(c in a)A.call(a,c)&&(b+=encodeURIComponent(c)+"="+encodeURIComponent(a[c])+"&");return j.location.pathname+b.slice(0,-1)},extend:l,id:k,addEvent:s});l(e.constructor.prototype,{begin:p("begin"),done:p("done"),log:p("log"),testStart:p("testStart"),testDone:p("testDone"),moduleStart:p("moduleStart"),moduleDone:p("moduleDone")});if("undefined"===typeof document||"complete"===document.readyState)d.autorun=!0;e.load=function(){m("begin",e,{});var a,c,b,f,h;f="";a=l({},
d);e.init();l(d,a);d.blocking=!1;b=d.urlConfig.length;for(a=0;a<b;a++)h=d.urlConfig[a],d[h]=e.urlParams[h],f+="<label><input name='"+h+"' type='checkbox'"+(d[h]?" checked='checked'":"")+">"+h+"</label>";if(a=k("qunit-userAgent"))a.innerHTML=navigator.userAgent;if(a=k("qunit-header"))a.innerHTML="<a href='"+e.url({filter:void 0})+"'>"+a.innerHTML+"</a> "+f,s(a,"change",function(a){var b={};b[a.target.name]=a.target.checked?!0:void 0;j.location=e.url(b)});if(f=k("qunit-testrunner-toolbar")){c=document.createElement("input");
c.type="checkbox";c.id="qunit-filter-pass";s(c,"click",function(){var a,b=document.getElementById("qunit-tests");c.checked?b.className+=" hidepass":(a=" "+b.className.replace(/[\n\t\r]/g," ")+" ",b.className=a.replace(/ hidepass /," "));q&&(c.checked?sessionStorage.setItem("qunit-filter-passed-tests","true"):sessionStorage.removeItem("qunit-filter-passed-tests"))});if(d.hidepassed||q&&sessionStorage.getItem("qunit-filter-passed-tests"))c.checked=!0,a=document.getElementById("qunit-tests"),a.className+=
" hidepass";f.appendChild(c);a=document.createElement("label");a.setAttribute("for","qunit-filter-pass");a.innerHTML="Hide passed tests";f.appendChild(a)}if(f=k("qunit-fixture"))d.fixture=f.innerHTML;d.autostart&&e.start()};s(j,"load",e.load);j.onerror=function(a,c,b){e.config.current?e.pushFailure(a,c+":"+b):e.test("global failure",function(){e.pushFailure(a,c+":"+b)})};e.equiv=function(){var a,c=[],b=[],d=Object.getPrototypeOf||function(a){return a.__proto__},h=function(){function g(a,b){return a instanceof
b.constructor||b instanceof a.constructor?b==a:b===a}return{string:g,"boolean":g,number:g,"null":g,undefined:g,nan:function(a){return isNaN(a)},date:function(a,b){return"date"===e.objectType(a)&&b.valueOf()===a.valueOf()},regexp:function(a,b){return"regexp"===e.objectType(a)&&b.source===a.source&&b.global===a.global&&b.ignoreCase===a.ignoreCase&&b.multiline===a.multiline},"function":function(){var a=c[c.length-1];return a!==Object&&"undefined"!==typeof a},array:function(c,d){var g,f,h,t;if("array"!==
e.objectType(c))return!1;h=d.length;if(h!==c.length)return!1;b.push(d);for(g=0;g<h;g++){t=!1;for(f=0;f<b.length;f++)b[f]===d[g]&&(t=!0);if(!t&&!a(d[g],c[g]))return b.pop(),!1}b.pop();return!0},object:function(i,e){var g,h,j,t=!0,k=[],l=[];if(e.constructor!==i.constructor&&!(null===d(e)&&d(i)===Object.prototype||null===d(i)&&d(e)===Object.prototype))return!1;c.push(e.constructor);b.push(e);for(g in e){j=!1;for(h=0;h<b.length;h++)b[h]===e[g]&&(j=!0);k.push(g);if(!j&&!a(e[g],i[g])){t=!1;break}}c.pop();
b.pop();for(g in i)l.push(g);return t&&a(k.sort(),l.sort())}}}();return a=function(){var a=[].slice.apply(arguments);if(2>a.length)a=!0;else{var b;if(a[0]===a[1])b=!0;else if(null===a[0]||null===a[1]||"undefined"===typeof a[0]||"undefined"===typeof a[1]||e.objectType(a[0])!==e.objectType(a[1]))b=!1;else{b=[a[1],a[0]];var c=e.objectType(a[0]);b=c?"function"===e.objectType(h[c])?h[c].apply(h,b):h[c]:void 0}a=b&&arguments.callee.apply(this,a.splice(1,a.length-1))}return a}}();e.jsDump=function(){function a(a){return'"'+
a.toString().replace(/"/g,'\\"')+'"'}function c(a){return a+""}function b(a,b,c){var d=g.separator(),e=g.indent(),f=g.indent(1);b.join&&(b=b.join(","+d+f));return!b?a+c:[a,f+b,e+c].join(d)}function d(a,c){var e=a.length,f=Array(e);for(this.up();e--;)f[e]=this.parse(a[e],void 0,c);this.down();return b("[",f,"]")}var h=/^function (\w+)/,g={parse:function(a,b,c){var c=c||[],d,e=this.parsers[b||this.typeOf(a)],b=typeof e;a:if(d=c,d.indexOf)d=d.indexOf(a);else{for(var f=0,h=d.length;f<h;f++)if(d[f]===
a){d=f;break a}d=-1}if(-1!=d)return"recursion("+(d-c.length)+")";return"function"==b?(c.push(a),a=e.call(this,a,c),c.pop(),a):"string"==b?e:this.parsers.error},typeOf:function(a){return null===a?"null":"undefined"===typeof a?"undefined":e.is("RegExp",a)?"regexp":e.is("Date",a)?"date":e.is("Function",a)?"function":void 0!==typeof a.setInterval&&"undefined"!==typeof a.document&&"undefined"===typeof a.nodeType?"window":9===a.nodeType?"document":a.nodeType?"node":"[object Array]"===D.call(a)||"number"===
typeof a.length&&"undefined"!==typeof a.item&&(a.length?a.item(0)===a[0]:null===a.item(0)&&"undefined"===typeof a[0])?"array":typeof a},separator:function(){return this.multiline?this.HTML?"<br />":"\n":this.HTML?"&nbsp;":" "},indent:function(a){if(!this.multiline)return"";var b=this.indentChar;this.HTML&&(b=b.replace(/\t/g,"   ").replace(/ /g,"&nbsp;"));return Array(this._depth_+(a||0)).join(b)},up:function(a){this._depth_+=a||1},down:function(a){this._depth_-=a||1},setParser:function(a,b){this.parsers[a]=
b},quote:a,literal:c,join:b,_depth_:1,parsers:{window:"[Window]",document:"[Document]",error:"[ERROR]",unknown:"[Unknown]","null":"null",undefined:"undefined","function":function(a){var c="function",d="name"in a?a.name:(h.exec(a)||[])[1];d&&(c+=" "+d);c=[c+"( ",e.jsDump.parse(a,"functionArgs"),"){"].join("");return b(c,e.jsDump.parse(a,"functionCode"),"}")},array:d,nodelist:d,arguments:d,object:function(a,c){var d=[],f,h,g,j;e.jsDump.up();if(Object.keys)f=Object.keys(a);else for(h in f=[],a)f.push(h);
f.sort();for(j=0;j<f.length;j++)h=f[j],g=a[h],d.push(e.jsDump.parse(h,"key")+": "+e.jsDump.parse(g,void 0,c));e.jsDump.down();return b("{",d,"}")},node:function(a){var b,c,d=e.jsDump.HTML?"&lt;":"<",f=e.jsDump.HTML?"&gt;":">",h=a.nodeName.toLowerCase(),g=d+h;for(b in e.jsDump.DOMAttrs)(c=a[e.jsDump.DOMAttrs[b]])&&(g+=" "+b+"="+e.jsDump.parse(c,"attribute"));return g+f+d+"/"+h+f},functionArgs:function(a){var b=a.length;if(!b)return"";for(a=Array(b);b--;)a[b]=String.fromCharCode(97+b);return" "+a.join(", ")+
" "},key:a,functionCode:"[code]",attribute:a,string:a,date:a,regexp:c,number:c,"boolean":c},DOMAttrs:{id:"id",name:"name","class":"className"},HTML:!1,indentChar:"  ",multiline:!0};return g}();e.diff=function(){return function(a,c){var a=a.replace(/\s+$/,""),c=c.replace(/\s+$/,""),b,d,e="",g=""===a?[]:a.split(/\s+/),i=""===c?[]:c.split(/\s+/);d={};var j={};for(b=0;b<i.length;b++)null==d[i[b]]&&(d[i[b]]={rows:[],o:null}),d[i[b]].rows.push(b);for(b=0;b<g.length;b++)null==j[g[b]]&&(j[g[b]]={rows:[],
n:null}),j[g[b]].rows.push(b);for(b in d)A.call(d,b)&&1==d[b].rows.length&&"undefined"!=typeof j[b]&&1==j[b].rows.length&&(i[d[b].rows[0]]={text:i[d[b].rows[0]],row:j[b].rows[0]},g[j[b].rows[0]]={text:g[j[b].rows[0]],row:d[b].rows[0]});for(b=0;b<i.length-1;b++)null!=i[b].text&&null==i[b+1].text&&i[b].row+1<g.length&&null==g[i[b].row+1].text&&i[b+1]==g[i[b].row+1]&&(i[b+1]={text:i[b+1],row:i[b].row+1},g[i[b].row+1]={text:g[i[b].row+1],row:b+1});for(b=i.length-1;0<b;b--)null!=i[b].text&&null==i[b-1].text&&
0<i[b].row&&null==g[i[b].row-1].text&&i[b-1]==g[i[b].row-1]&&(i[b-1]={text:i[b-1],row:i[b].row-1},g[i[b].row-1]={text:g[i[b].row-1],row:b-1});var j=a.match(/\s+/g),k=c.match(/\s+/g);null==j?j=[" "]:j.push(" ");null==k?k=[" "]:k.push(" ");if(0===i.length)for(b=0;b<g.length;b++)e+="<del>"+g[b]+j[b]+"</del>";else{if(null==i[0].text)for(c=0;c<g.length&&null==g[c].text;c++)e+="<del>"+g[c]+j[c]+"</del>";for(b=0;b<i.length;b++)if(null==i[b].text)e+="<ins>"+i[b]+k[b]+"</ins>";else{d="";for(c=i[b].row+1;c<
g.length&&null==g[c].text;c++)d+="<del>"+g[c]+j[c]+"</del>";e+=" "+i[b].text+k[b]+d}}return e}}();"undefined"!==typeof exports&&l(exports,e)})(function(){return this}.call());
